version: '3.8'

services:
  api:
    build: 
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cv_db
    depends_on:
      - db
    volumes:
      - ./src:/app
      - /app/.venv/
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: